use crate::clipboard::{MAX_ITEM_BYTES, Raw};
use anyhow::{Context, Result, ensure};
use objc2::{
    class, msg_send,
    rc::{Retained, autoreleasepool},
    runtime::AnyObject,
};
use objc2_foundation::{NSArray, NSData, NSString, NSURL};
use std::{ffi::CStr, os::unix::ffi::OsStrExt, path::PathBuf};

pub struct Clipboard {
    board: Retained<AnyObject>,
}
impl Clipboard {
    pub fn new() -> Result<Self> {
        Ok(autoreleasepool(|_| Self {
            board: unsafe { msg_send![class!(NSPasteboard), generalPasteboard] },
        }))
    }
    pub fn sequence(&self) -> u64 {
        autoreleasepool(|_| unsafe {
            let count: isize = msg_send![&self.board, changeCount];
            count as u64
        })
    }
    pub fn read(&mut self) -> Result<Option<Raw>> {
        autoreleasepool(|_| unsafe {
            let types: Option<Retained<NSArray<NSString>>> = msg_send![&self.board, types];
            if types.as_ref().is_some_and(|types| {
                types.iter().any(|ty| {
                    matches!(
                        ty.to_string().as_str(),
                        "org.nspasteboard.ConcealedType"
                            | "org.nspasteboard.TransientType"
                            | "org.nspasteboard.AutoGeneratedType"
                    )
                })
            }) {
                return Ok(None);
            }
            let filenames: Option<Retained<NSArray<NSString>>> = msg_send![&self.board, propertyListForType: &*NSString::from_str("NSFilenamesPboardType")];
            if let Some(files) = filenames.filter(|files| !files.is_empty()) {
                ensure!(files.len() <= 1000, "剪贴板文件数量过多");
                return Ok(Some(Raw::Files(
                    files.iter().map(|s| PathBuf::from(s.to_string())).collect(),
                )));
            }
            // Modern Finder and other apps publish one public.file-url per item.
            let items: Option<Retained<NSArray<AnyObject>>> =
                msg_send![&self.board, pasteboardItems];
            let mut paths = Vec::new();
            if let Some(items) = items {
                ensure!(items.len() <= 1000, "剪贴板项目数量过多");
                for item in items.iter() {
                    let string: Option<Retained<NSString>> =
                        msg_send![&item, stringForType: &*NSString::from_str("public.file-url")];
                    if let Some(url) = string.and_then(|s| NSURL::URLWithString(&s)) {
                        let file: bool = msg_send![&url, isFileURL];
                        if file {
                            paths.push(PathBuf::from(std::ffi::OsStr::from_bytes(
                                CStr::from_ptr(url.fileSystemRepresentation().as_ptr()).to_bytes(),
                            )));
                        }
                    }
                }
            }
            if !paths.is_empty() {
                return Ok(Some(Raw::Files(paths)));
            }
            for (ty, mime) in [
                ("public.png", "image/png"),
                ("public.tiff", "image/tiff"),
                ("public.jpeg", "image/jpeg"),
                ("org.webmproject.webp", "image/webp"),
                ("com.compuserve.gif", "image/gif"),
                ("com.microsoft.bmp", "image/bmp"),
            ] {
                let data: Option<Retained<NSData>> =
                    msg_send![&self.board, dataForType: &*NSString::from_str(ty)];
                if let Some(data) = data {
                    ensure!(data.len() <= MAX_ITEM_BYTES, "剪贴板图片过大");
                    return Ok(Some(Raw::Image {
                        mime: mime.into(),
                        bytes: data.to_vec(),
                    }));
                }
            }
            let text: Option<Retained<NSString>> = msg_send![&self.board, stringForType: &*NSString::from_str("public.utf8-plain-text")];
            if let Some(text) = text {
                ensure!(text.len() <= MAX_ITEM_BYTES, "剪贴板文本过大");
                return Ok(Some(Raw::Text(text.to_string())));
            }
            Ok(None)
        })
    }
    pub fn write(&mut self, raw: &Raw) -> Result<()> {
        autoreleasepool(|_| unsafe {
            let _: isize = msg_send![&self.board, clearContents];
            let success: bool = match raw {
                Raw::Text(text) => {
                    msg_send![&self.board, setString: &*NSString::from_str(text), forType: &*NSString::from_str("public.utf8-plain-text")]
                }
                Raw::Image { mime, bytes } => {
                    let ty = match mime.as_str() {
                        "image/png" => "public.png",
                        "image/tiff" => "public.tiff",
                        "image/jpeg" => "public.jpeg",
                        "image/webp" => "org.webmproject.webp",
                        "image/gif" => "com.compuserve.gif",
                        "image/bmp" => "com.microsoft.bmp",
                        _ => anyhow::bail!("不支持的图片格式"),
                    };
                    msg_send![&self.board, setData: &*NSData::with_bytes(bytes), forType: &*NSString::from_str(ty)]
                }
                Raw::Files(paths) => {
                    let urls: Vec<_> = paths
                        .iter()
                        .map(|p| NSURL::from_file_path(p).context("文件路径无效"))
                        .collect::<Result<_>>()?;
                    let objects = NSArray::from_retained_slice(&urls);
                    msg_send![&self.board, writeObjects: &*objects]
                }
            };
            ensure!(success, "剪贴板写入失败，请重试");
            Ok(())
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn isolated_native_pasteboard_roundtrips_text_image_and_file_urls() {
        // Never inspect or overwrite the user's general pasteboard in tests.
        autoreleasepool(|_| unsafe {
            let name = NSString::from_str(&format!("starter-test-{}", std::process::id()));
            let board = msg_send![class!(NSPasteboard), pasteboardWithName: &*name];
            let mut clipboard = Clipboard { board };
            let dir = tempfile::tempdir().unwrap();
            let path = dir.path().join("中文 file & name.txt");
            std::fs::write(&path, "fixture").unwrap();
            let raw = [
                Raw::Text("test\n中文 https://example.org".into()),
                crate::clipboard::tests::png(),
                Raw::Files(vec![path]),
            ];
            for item in &raw {
                let sequence = clipboard.sequence();
                clipboard.write(item).unwrap();
                assert_ne!(sequence, clipboard.sequence());
                assert_eq!(clipboard.read().unwrap().as_ref(), Some(item));
            }
            clipboard
                .write(&Raw::Text("private fixture".into()))
                .unwrap();
            let _: bool = msg_send![&clipboard.board, setString: &*NSString::from_str("1"), forType: &*NSString::from_str("org.nspasteboard.ConcealedType")];
            assert_eq!(clipboard.read().unwrap(), None);
            let _: () = msg_send![&clipboard.board, releaseGlobally];
        });
    }
}
